github: [https://github.com/sponsors/helloharendra]
patreon: https://www.patreon.com/helloharendra
open_collective: https://opencollective.com/helloharendra
ko_fi: https://ko-fi.com/helloharendra
tidelift: https://tidelift.com/subscription/pkg/npm-helloharendra
community_bridge: https://communitybridge.org/helloharendra
liberapay: https://liberapay.com/helloharendra
issuehunt: https://issuehunt.io/r/helloharendra
lfx_crowdfunding: https://lfx.io/projects/helloharendra
polar: https://polar.me/helloharendra
buy_me_a_coffee: https://www.buymeacoffee.com/helloharendra
thanks_dev: https://thanks.dev/helloharendra
custom:
  - https://nayaprayog.com
